x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
      
services:
  dummy-pdf-or-png:
    image: ${DOCKER_REGISTRY-}dummy-pdf-or-png
    build:
      context: ../dummy-pdf-or-png
      dockerfile: Dockerfile
    logging: *loki-logging
    networks:
      - assignment
    
  assignment-service:
    image: ${DOCKER_REGISTRY-}assignment-service
    build:
      context: ../assignment-service
      dockerfile: Dockerfile
    logging: *loki-logging
    environment:
      ASS_ServiceConfig__DummyPdfOrPngServiceRoot: http://dummy-pdf-or-png:3000
    ports:
      - 3020:80
    networks:
      - assignment
  
  loki:
    image: grafana/loki:2.6.1
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - 3100:3100
    networks:
      - assignment
  
  prometheus:
    image: prom/prometheus:v2.37.0
    ports:
      - 9090:9090
    volumes:
      - ../prometheus:/etc/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - assignment
    
  grafana:
    image: grafana/grafana:9.0.5
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ../grafana/datasources-compose.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    logging: *loki-logging
    ports:
      - 3050:3000
    networks:
      - assignment
networks:
  assignment:
      
