parameters:
  - name: allowDestructivePlan
    displayName: Allow Terraform destroy resources?
    type: boolean
    default: false

name: 0.0.1$(Rev:.r)_$(SourceBranchName)
trigger:
  batch: true
  branches:
    include:
      - master
pool:
  vmImage: 'ubuntu-latest'

variables:
  TF_IN_AUTOMATION: true
  TF_INPUT: 0

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - template: templates/build.yml
  - stage: DEV
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: 'sre-assignment'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deploy.yml
                  parameters:
                    environmentName: 'sre-assignment'
                    allowDestructivePlan: '${{ parameters.allowDestructivePlan }}'
                  
        
