parameters:
  - name: allowDestructivePlan
    displayName: Allow Terraform destroy resources?
    type: boolean
    default: false

name: 0.0.1$(Rev:.r)_$(SourceBranchName)
trigger:
  batch: true
  branches:
    include:
      - master
pool:
  vmImage: 'windows-latest'

variables:
  TF_IN_AUTOMATION: true
  TF_INPUT: 0
  ADO_ORG_SERVICE_URL: https://dev.azure.com/pikatpavel/

stages:
  - stage: Infrastructure
    jobs:
      - deployment: Infrastructure
        environment: 'sre-assignment-infrastructure'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/infrastructure.yml
                  parameters:
                    environmentName: 'sre-assignment-infrastructure'
                    allowDestructivePlan: '${{ parameters.allowDestructivePlan }}'
  - stage: Build
    dependsOn: Infrastructure
    jobs:
      - job: BuildDummyPdf
        steps:
          - template: templates/build.yml
            parameters:
              dockerFile: '$(Build.SourcesDirectory)\sre\dummy-pdf-or-png\Dockerfile'
      - job: BuildAssignmentService
        steps:
          - template: templates/build.yml
            parameters:
              dockerFile: '$(Build.SourcesDirectory)\sre\dummy-pdf-or-png\Dockerfile'

                  
        
