apiVersion: v1
kind: Namespace
metadata:
  name: visma-assignment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-service
  namespace: visma-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment-service
  template:
    metadata:
      labels:
        app: assignment-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: assignment-service
          env:
            - name: ASS_ServiceConfig__DummyPdfOrPngServiceRoot
              value: http://dummy-pdf-or-png:3000/
          image: sreassignmentacr.azurecr.io/assignment-service:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-pdf-or-png-service
  namespace: visma-assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-pdf-or-png
  template:
    metadata:
      labels:
        app: dummy-pdf-or-png
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: dummy-pdf-or-png
          image: sreassignmentacr.azurecr.io/dummy-pdf-or-png:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: assignment-service-entrypoint
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: visma-assignment-service
  namespace: visma-assignment
spec:
  type: LoadBalancer
  selector:
    app: assignment-service
  ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-pdf-or-png
  namespace: visma-assignment
spec:
  selector:
    app: dummy-pdf-or-png
  ports:
    - port: 3000
      protocol: TCP
