parameters:
  dockerFile: ''
  repository: ''
  
steps:
  - checkout: self
    
  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      command: buildAndPush
      repository: '${{ parameters.repository }}'
      dockerfile: '${{ parameters.dockerFile }}'
      containerRegistry: 'e-conomic AzureCR'
      tags: |
        latest
